### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by BasToTheMax** [mineglade/dynamic-bungee#5]
Is this project still alive or is the development dead?

**Comment by mia-riezebos** [comment]
Hi, you're always welcome to fork and PR improvements or fixes. I check out my notifications almost daily (although I should unwatch some repos so I don't miss important notifications). 

Over the past couple of months I've had to move out, find a new place, and I still have school and a day job, so I haven't had time to work on this project.
I've finally settled in a new place, closer to both school and my job, meaning I'll probably find more time to work on dynbun in the future, but I can't make any promises about a timeline.

Thanks for your interest in the project though!
