### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by BasToTheMax** [mineglade/dynamic-bungee#8]
Add mysql so it loads the servers when the proxy starts

**Comment by mia-riezebos** [comment]
I understand the feature request but I believe this is slightly outisde the scope of this project as of now. 
When the proxy starts, It will check its own config file (written to disk), and load the servers from that configuration file. This reduces an extra liability of a database that could be down at time of boot, and saves code for connection checking.

If you were running multiple proxies for load balancing, I believe you should already be using scalable solutions like RedisBungee.

If you believe that I am wrong for saying this and would really like this plugin to turn into a hybrid testing / load balancing plugin, let me know.
